/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MrsButton {
    }
}
declare global {
    interface HTMLMrsButtonElement extends Components.MrsButton, HTMLStencilElement {
    }
    var HTMLMrsButtonElement: {
        prototype: HTMLMrsButtonElement;
        new (): HTMLMrsButtonElement;
    };
    interface HTMLElementTagNameMap {
        "mrs-button": HTMLMrsButtonElement;
    }
}
declare namespace LocalJSX {
    interface MrsButton {
    }
    interface IntrinsicElements {
        "mrs-button": MrsButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mrs-button": LocalJSX.MrsButton & JSXBase.HTMLAttributes<HTMLMrsButtonElement>;
        }
    }
}
